apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: klm-local
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 80
        hostPort: 80
      - containerPort: 443
        hostPort: 443
        # 0.0.0.0 is the current default
#        listenAddress: "127.0.0.1"
